### ISSUE TITLE
Two automations for two gates deliver different times to the input_datetime.automatic_gate_planned_opening

### ISSUE THREAD

**Issue by manuelmrmorgado** [etiennec78/Home-Automation#8] opened 2024-10-08 22:39 UTC
### Describe the bug

As discussed in the community forum. Gates don't open at the same time. I cannot use one automation for both gates as only the garage gate is fully controlled by the automation. The front gate closes automatically.

### Expected behavior

I expected both gates to open at the same time, having the lead in time the same for both automations, as the input_datetime.automatic_gate_planned_opening should be input the same by both automations.
As I drive a Tesla and I have arrival time sensors as timestamp, may I suggest being possible to use that instead of Waze calculations?

### Blueprint configuration

alias: Gate - Automatic Front Gate ⛩️
description: ""
use_blueprint:
  path: etiennec78/automatic-gate.yaml
  input:
    gate:
      - switch.front_gate
    lead_time: 60
    safety_delay: 1
    persons:
      - person.tesla
    driving_sensors:
      - binary_sensor.tesla_driving
    travel_time_sensors:
      - sensor.tesla_travel_time
    proximity_sensors:
      - sensor.home_tesla_distance
    notify_devices:
      - manuels_iphone_15_pro
    itinerary_sensors:
      - input_text.tesla_itinerary
    eta_sensor: input_datetime.automatic_gate_planned_opening
    automatic_closing_arrival: false
    activation_zone: 600
    automatic_closing: "off"
    auto_close_arrival_delay: 0
    ble_transmitter_phone_control: false
    gate_opening_title: Gate opening 🔓
    ble_entities: []

alias: Gate - Automatic Garage Gate ⛩️
description: ""
use_blueprint:
  path: etiennec78/automatic-gate.yaml
  input:
    gate:
      - cover.garage_gate
    lead_time: 60
    eta_sensor: input_datetime.automatic_gate_planned_opening
    persons:
      - person.tesla
    driving_sensors:
      - binary_sensor.tesla_driving
    travel_time_sensors:
      - sensor.tesla_travel_time
    proximity_sensors:
      - sensor.home_tesla_distance
    itinerary_sensors:
      - input_text.tesla_itinerary
    notify_devices:
      - manuels_iphone_15_pro
    activation_zone: 600
    automatic_closing: "on"
    auto_close_arrival_delay: 0
    gate_opening_title: Garage opening 🔓
    gate_closing_title: Garage closing 🔒
    awaiting_title: Garage awaiting {{ awaiting_persons }} 💤
    automatic_opening_message: Automatic opening of the garage
    automatic_closing_message: Automatic closing of the garage
    awaiting_message: The garage will close once all users have entered/exited
    ble_transmitter_phone_control: false
    safety_delay: 2
    ble_entities:
      - sensor.tesla_distance_to_garage_gate

### Blueprint traces

[trace automation.automatic_front_gate 2024-10-08T14_21_19.227620+00_00.json]()
[trace automation.automatic_garage_gate 2024-10-08T14_21_19.231309+00_00.json]()

### What version of Home Assistant are you running ?

core-2024.10.1

### What type of installation are you running?

Home Assistant OS

**Comment by etiennec78** [comment] 2024-12-02 18:44
Sorry, I just saw that I had completely forgotten to close the issue here...
After reading your two log files, I deduced that the problem came from Waze, which seems to have estimated a much higher ETA for one automation than for the other.
And because of the way HA blueprints work, each one waited for the ETA value when evaluating, and didn't update if another had updated it.
However, I can't see the value returned by Waze and I can't be 100% sure that this is the cause.

But since I've added multiple gates support, everything should work now !

**Closed as completed** 2024-12-02 18:44 UTC
Labels: bug
